### PR TITLE
Php71

### PR DESCRIPTION
**Pull request by mambax7**
Few changes for PHP 7.1. Maybe you can run it as a separate branch?

### CODE REVIEW

**Comment by kilica** [comment]
https://github.com/xoopscube/xcl/pull/186/commits/f3df9ddaa3b45c369e2903d04fda4dd506f67061
`?:` can be used after PHP 7.0. 
If new xcl will support PHP5.6.x, revert this change.

**Comment by mambax7** [comment]
Sure, if PHP 5.6 is the minimum version, I'll be happy to revert it. 
 
Michael

  _____

**Comment by kilica** [comment]
Sorry, Mamba.
The former my comment is my mistake, ?: is from PHP5.3( ?? is from 7.1).
No need to revert your commits.

**Comment by mambax7** [comment]
OK, thanks for the clarification! 
And Happy New Year to you, your family, and to the whole XOOPS community!!

**Pull request merged**
